title: Gabriel Marinho
lang: pt_BR
email: gdcmarinho@gmail.com
description: >- 
  Trabalhando com desenvolvimento web desde 2013, criando projetos que
  impactam milhares de pessoas. Sempre preocupado com a experiência do
  usuário e usando métricas de dados para otimizar ferramentas web
baseurl: "/" 
url: "gabrielmarinho.tech" 
twitter_username: OfficialMarinho
github_username:  OfficialMarinho

theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag